### ISSUE TITLE
Not work with Chinese characters

### ISSUE THREAD

**Issue by xuchunyang** [emacs-pe/gh-md.el#2]
The left is the rendered result, the right is the Markdown source containing some Chinese characters:
![screen shot 2015-03-01 at 5 04 09 am](https://cloud.githubusercontent.com/assets/4550353/6428141/d0fe6284-bfd0-11e4-8f5d-df5af91f4026.png)

Below is partial testing Markdown source, just in case you want to try by yourself

```
# Search Chinese by Pinyin

---

## Introduction

Search Chinese by the first letter of Chinese pinyin.

使用拼音首字母搜索中文。

e.g. use `zw` to search `中文` (*Z*hong *W*en).

This package is similar to
[vim-PinyinSearch](https://github.com/ppwwyyxx/vim-PinyinSearch), but
probably more powerful for
[Incremental Search](http://www.gnu.org/software/emacs/manual/html_node/emacs/Incremental-Search.html)
and Emacs itself.

```

**Comment by marsam** [comment]
Hi:
Thanks for reporting. I've pushed a fix, tell me if it works

**Comment by xuchunyang** [comment]
It works fine now. Thank you for your work.
