### ISSUE TITLE
"peculiar error"

### ISSUE THREAD

**Issue by LionyxML** [emacs-pe/gh-md.el#7]
Hello there.

I am getting this on my *Messages* buffer when I try to use gh-md.

![image](https://user-images.githubusercontent.com/16169950/158100546-0978e661-059b-46b1-ae43-8d441f0c27ac.png)

 Nothing happens on the buffer when issuing the command.

**Comment by tarsius** [comment]
I cannot reproduce, so I'll need a backtrace from you.

**Comment by tarsius** [comment]
Oh, I see you write elisp yourself. Please try to investigate this yourself. As you can imagine I am quite busy maintaining magit and such and thus appreciate all help I can get taking care of the orphans.

**Comment by LionyxML** [comment]
Sorry I haven't seen before this package belongs to the orphanage :D

I'll take a deep look at this later. Thanks for confirm it is fine in your end.

**Comment by LionyxML** [comment]
Well it works now!

I had to "reconfigure" git:
```
git config --global --unset http.proxy 
git config --global --unset https.proxy
```

If you're interest in keep this config note inside package doc I made a PR.
