### ISSUE TITLE
does not render collapssible

### ISSUE THREAD

**Issue by erwannr** [emacs-pe/gh-md.el#9]
Copied from [this](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab#how-to-structure):

```
 # A collapsible section with markdown
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

```
Renders:

> A collapsible section with markdown
> 
> Click to expand!
> 
> Heading
> 
> 1 A numbered
> 2 list 
> 
>  * With some
>  * Sub bullets
> 

where is expected:

> ▶Click to expand!

and clicking on ▶ expands the content.

**Comment by tarsius** [comment]
`shr` does not appear to support `<detail>`. The library commentary is:

> ;; This package takes a HTML parse tree (as provided by
> ;; libxml-parse-html-region) and renders it in the current buffer.  It
> ;; does not do CSS, JavaScript or anything advanced: It's geared
> ;; towards rendering typical short snippets of HTML, like what you'd
> ;; find in HTML email and the like.

But still, maybe `<detail>` is in scope for `shr`, you might want to request that feature using `report-emacs-bug`.
